package project.sgs.Exeption;

public enum ErrorCode {
    ARTICLE_NOT_FOUND(1000),
    ARTICLE_NOT_VALIDE(1001),
    CATEGORIE_NOT_FOUND(2000),
    CATEGORIE_NOT_VALID(2001),
    CLIENT_NOT_FOUND(3000),
    CLIENT_NOT_VALID(3001),
    COMMANDE_CLIENT_NOT_FOUND(4000),
    COMMANDE_CLIENT_NOT_VALID(4001),
    COMMANDE_CLIENT_NOT_MODIFIABLE(4002),
    COMMANDE_FOURINISSEURE_NOT_FOUND(5000),
    COMMANDE_FOURINISSEURE_NOT_VALID(5001),
    FOURINISSEURE_NOT_FOUND(7000),
    FOURINISSEURE_NOT_VALID(7001),
    LIGNE_COMMANDE_FOURNISSEURE_NOT_FOUND(8000),
    LIGNE_COMMANDE_CLIENT_NOT_FOUND(9000),
    LIGNE_VENTE_NOT_FOUND(10000),
    UTILISATEURE_NOT_FOUND(11000),
    UTILISATEURE_NOT_VALID(11001),
    VENTE_NOT_FOUND(12000),
    VENTE_NOT_VALID(12001),
    MVM_STOCK_NOT_FOUND(13000),
    Context_NOT_FOUND(14000);
    ;
    private int code;
    ErrorCode(int code){
        this.code=code;
    }
    public int getCode(){
        return code;
    }
}
